---

#Security configuration
- name: include security/elasticsearch-security.yml
  include: security/elasticsearch-security.yml
  when: es_enable_xpack

#Make sure elasticsearch.keystore has correct Permissions
- name: Set elasticsearch.keystore Permissions
  become: yes
  file: state=file path={{ es_conf_dir }}/elasticsearch.keystore owner={{ es_user }} group={{ es_group }}
  when: es_enable_xpack
